CREATE TABLE songs (
    id SERIAL PRIMARY KEY,
    lastfm_mbid VARCHAR(64),
    lastfm_title VARCHAR(255),
    lastfm_artist VARCHAR(255),
    lastfm_url TEXT,
    lastfm_playcount INTEGER,
    lastfm_listeners INTEGER,
    spotify_id VARCHAR(64),
    spotify_title VARCHAR(255),
    spotify_artist VARCHAR(255),
    spotify_album VARCHAR(255),
    spotify_popularity INTEGER,
    spotify_duration_ms INTEGER,
    spotify_url TEXT,
    reccobeats_id VARCHAR(64),
    acousticness FLOAT,
    danceability FLOAT,
    energy FLOAT,
    instrumentalness FLOAT,
    liveness FLOAT,
    loudness FLOAT,
    speechiness FLOAT,
    tempo FLOAT,
    valence FLOAT
);